language: python
python: 3.8
env:
  - TOXENV=checkmanifest

matrix:
  include:
  - python: 3.6
    env: TOXENV=py36-django22-test
  - python: 3.6
    env: TOXENV=py36-django30-test
  - python: 3.6
    env: TOXENV=py36-django31-test

  - python: 3.9-dev
    env: TOXENV=py39-django22-test
  - python: 3.9-dev
    env: TOXENV=py39-django30-test
  - python: 3.9-dev
    env: TOXENV=py39-django31-test

  - python: 3.8
    env: TOXENV=py38-flake

install:
  - pip install coveralls tox>=2.1
script:
  - tox
after_script:
  - coveralls
sudo: false
